title: "Daniel Joseph Aronoff: Academic Website"
description: "Daniel Joseph Aronoff (Dan J. Aronoff, Dan Aronoff) is an economist at MIT working at the intersection of market design, cryptography, and digital currencies."
url: "https://danieljaronoff.github.io"
baseurl: ""
# Override this with your primary canonical domain.
# Keep this set to your canonical public domain.
seo_base_url: "https://danieljaronoff.github.io"
lang: "en"
timezone: "America/New_York"
author:
  name: "Daniel Joseph Aronoff"
  email: "daronoff@mit.edu"
  url: "https://danieljaronoff.github.io"
  same_as:
    - "https://www.linkedin.com/in/daniel-aronoff-968a19b0/"
    - "https://www.mit.edu"
markdown: kramdown
permalink: pretty
include:
  - _pages
sass:
  sass_dir: _sass
  style: compressed
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/img/daniel-joseph-aronoff-portrait.jpeg"
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - scripts
  - .github
  - .devcontainer
  - .vscode
  - vendor
  - node_modules

# republish_marker: 2026-03-12T02:45:00Z
